version: '3.8'

services:
  ml-backend:
    build: .
    container_name: ssc-cgl-ml-backend
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./models:/app/models
      - ./chroma_db:/app/chroma_db
    depends_on:
      - redis
      - neo4j
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ssc-cgl-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  neo4j:
    image: neo4j:5.13
    container_name: ssc-cgl-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    restart: unless-stopped

volumes:
  redis_data:
  neo4j_data:
